dist: xenial
sudo: required 
language: minimal
services:
  - docker

matrix:
  include:
    - os: linux
      env:
        - DOCKER_IMAGE=fedora:30
        - BUILD_GENERATOR=Ninja
        - CI=1
    - os: linux
      env:
        - DOCKER_IMAGE=fedora:29
        - BUILD_GENERATOR=Ninja
        - CI=1
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu:focal
        - CI=1
        - CC=gcc-9
        - CXX=g++-9
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu:bionic
        - BUILD_GENERATOR=Ninja
        - CI=1
        - CC=gcc-8
        - CXX=g++-8
script:
  - ci/build-in-docker.sh ${DOCKER_IMAGE}
